var global_languages;
// var global_themes;

// global_themes = {
//     Chrome: "Chrome",
//     Clouds: "Clouds",
//     Crimson_Editor: "Crimson_Editor",
//     Dawn: "Dawn",
//     Dreamweaver: "Dreamweaver",
//     Eclipse: "Eclipse",
//     Github: "GitHub",
//     IPlastic: "IPlastic",
//     Solarized_Light: "Solarized_Light",
//     TextMate: "TextMate",
//     Tomorrow: "Tomorrow",
//     Xcode: "Xcode",
//     Kuroir: "Kuroir",
//     KatzenMilch: "KatzenMilch",
//     SQL_Server: "sqlserver",
//     Ambiance: "ambiance",
//     Chaos: "chaos",
//     Clouds_Midnight: "clouds_midnight",
//     Dracula: "",
//     Cobalt: "cobalt",
//     Gruvbox: "gruvbox",
//     Green_on_Black: "gob",
//     idle_Fingers: "idle_fingers",
//     krTheme: "kr_theme",
//     Merbivore: "merbivore",
//     Merbivore_Soft: "merbivore_soft",
//     Mono_Industrial: "mono_industrial",
//     Monokai: "monokai",
//     Nord_Dark: "nord_dark",
//     Pastel_on_dark: "pastel_on_dark",
//     Solarized_Dark: "solarized_dark",
//     Terminal: "terminal",
//     Tomorrow_Night: "tomorrow_night",
//     Tomorrow_Night_Blue: "tomorrow_night_blue",
//     Tomorrow_Night_Bright: "tomorrow_night_bright",
//     Tomorrow_Night_80s: "tomorrow_night_eighties",
//     Twilight: "twilight",
//     Vibrant_Ink: "vibrant_ink"
// }

global_languages = [
    "ABAP",
    "ABC",
    "ActionScript",
    "ADA",
    "Alda",
    "Apache_Conf",
    "Apex",
    "AQL",
    "AsciiDoc",
    "ASL",
    "Assembly_x86",
    "AutoHotKey",
    "BatchFile",
    "C_Cpp",
    "C9Search",
    "Cirru",
    "Clojure",
    "Cobol",
    "coffee",
    "ColdFusion",
    "Crystal",
    "CSharp",
    "Csound_Document",
    "Csound_Orchestra",
    "Csound_Score",
    "CSS",
    "Curly",
    "D",
    "Dart",
    "Diff",
    "Dockerfile",
    "Dot",
    "Drools",
    "Edifact",
    "Eiffel",
    "EJS",
    "Elixir",
    "Elm",
    "Erlang",
    "Forth",
    "Fortran",
    "FSharp",
    "FSL",
    "FTL",
    "Gcode",
    "Gherkin",
    "Gitignore",
    "Glsl",
    "Gobstones",
    "golang",
    "GraphQLSchema",
    "Groovy",
    "HAML",
    "Handlebars",
    "Haskell",
    "Haskell_Cabal",
    "haXe",
    "Hjson",
    "HTML",
    "HTML_Elixir",
    "HTML_Ruby",
    "INI",
    "Io",
    "Jack",
    "Jade",
    "Java",
    "JavaScript",
    "JSON",
    "JSON5",
    "JSONiq",
    "JSP",
    "JSSM",
    "JSX",
    "Julia",
    "Kotlin",
    "LaTeX",
    "LESS",
    "Liquid",
    "Lisp",
    "LiveScript",
    "LogiQL",
    "LSL",
    "Lua",
    "LuaPage",
    "Lucene",
    "Makefile",
    "Markdown",
    "Mask",
    "MATLAB",
    "Maze",
    "MediaWiki",
    "MEL",
    "MIXAL",
    "MUSHCode",
    "MySQL",
    "Nginx",
    "Nim",
    "Nix",
    "NSIS",
    "Nunjucks",
    "ObjectiveC",
    "OCaml",
    "Pascal",
    "Perl",
    "Perl6",
    "pgSQL",
    "PHP",
    "PHP_Laravel_blade",
    "Pig",
    "Powershell",
    "Praat",
    "Prisma",
    "Prolog",
    "Properties",
    "Protobuf",
    "Puppet",
    "Python",
    "QML",
    "R",
    "Razor",
    "RDoc",
    "Red",
    "RHTML",
    "RST",
    "Ruby",
    "Rust",
    "SASS",
    "SCAD",
    "Scala",
    "Scheme",
    "SCSS",
    "SH",
    "SJS",
    "Slim",
    "Smarty",
    "snippets",
    "Soy_Template",
    "Space",
    "SQL",
    "SQLServer",
    "Stylus",
    "SVG",
    "Swift",
    "Tcl",
    "Terraform",
    "Tex",
    "Text",
    "Textile",
    "Toml",
    "TSX",
    "Twig",
    "Typescript",
    "Vala",
    "VBScript",
    "Velocity",
    "Verilog",
    "VHDL",
    "Visualforce",
    "Wollok",
    "XML",
    "XQuery",
    "YAML",
    "Zeek",
    "Django"
];

export {global_languages};